### ISSUE TITLE
mrp plan wizard can't install test ...

### ISSUE THREAD

**Issue by jaronemo** [wt-io-it/odoo-addons#1]
Dears

can't install this module test..

![image](https://cloud.githubusercontent.com/assets/8476734/14432483/fc6ec74e-003c-11e6-91ef-67152ddfa0d4.png)

**Comment by wtaferner** [comment]
@jaronemo 
I don't know your installation but I guess this issue should be solved with https://github.com/wt-io-it/odoo-addons/commit/3960a3138b1fc6fe2d28aed5eb6cad37c3c24b88
