### ISSUE TITLE
ParseError: "External ID not found in the system: custom_backend.product_template_tree_view"

### ISSUE THREAD

**Issue by ConfiserieJonas** [wt-io-it/odoo-addons#3]
It seems there is some error in the code that makes odoo not able to find the External ID for  custom_backend.product_template_tree_view
Which is needed in the file mrp_labeling/views/product.xml
<field name="inherit_id" ref="custom_backend.product_template_tree_view"/>

File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 899, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: custom_backend.product_template_tree_view" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/mrp_labeling/views/product.xml:4, near
<record id="product_template_tree_view" model="ir.ui.view">
            <field name="name">product.template.product.tree</field>
            <field name="model">product.template</field>
            <field name="inherit_id" ref="custom_backend.product_template_tree_view"/>
            <field name="arch" type="xml">
                <field name="name" position="after">
                    <field name="calculated_norm_weight" string="Berechnet pro ME (g)"/>
                    <field name="norm_weight" string="Gewogen pro ME (g)"/>
                    <field name="deviation" string="Abweichung (%)"/>
                </field>
            </field>
        </record>

**Comment by wtaferner** [comment]
Thank you for reporting. It has been fixed in b71c4a3.
