### ISSUE TITLE
Field emplyee_id does not exists

### ISSUE THREAD

**Issue by ConfiserieJonas** [wt-io-it/odoo-addons#4]
File "/opt/odoo/odoo-server/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
veld(en) `arch` niet juist wegen beperking: Invalid view definition

Meer info over fout:
Veld employee_id` bestaat niet

Fout context:
Weergave`mrp.production.form`
[view_id: 1614, xml_id: n/b, model: mrp.production, parent_id: 873]" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/mrp_labeling/views/mrp_production.xml:4, near
<record id="mrp_production_form_view" model="ir.ui.view">
            <field name="name">mrp.production.form</field>
            <field name="model">mrp.production</field>
            <field name="inherit_id" ref="mrp.mrp_production_form_view"/>
            <field name="arch" type="xml">
                <data><field name="date_planned" position="after">
                    <field name="employee_id" required="True"/>
                </field>
                <notebook position="before">
                    <group>
                        <group>
                            <field name="life_date"/>
                            <field name="use_date"/>
                        </group>
                        <group>
                            <field name="removal_date"/>
                            <field name="alert_date"/>
                        </group>
                    </group>
                </notebook>
            </data></field>
        </record>

**Comment by wtaferner** [comment]
Thank you for reporting. It has been fixed in b71c4a3.
