### ISSUE TITLE
error context: view `mrp.production.form`

### ISSUE THREAD

**Issue by ConfiserieJonas** [wt-io-it/odoo-addons#5]
Fout context:
Weergave`mrp.production.form`
[view_id: 1630, xml_id: n/b, model: mrp.production, parent_id: 873]" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/mrp_labeling/views/mrp_production.xml:4, near
<record id="mrp_production_form_view" model="ir.ui.view">
            <field name="name">mrp.production.form</field>
            <field name="model">mrp.production</field>
            <field name="inherit_id" ref="mrp.mrp_production_form_view"/>
            <field name="arch" type="xml">
                <data><field name="date_planned" position="after">
                    <field name="employee_id" required="True"/>
                </field>
                <notebook position="before">
                    <group>
                        <group>
                            <field name="life_date"/>
                            <field name="use_date"/>
                        </group>
                        <group>
                            <field name="removal_date"/>
                            <field name="alert_date"/>
                        </group>
                    </group>
                </notebook>
            </data></field>
        </record>

**Comment by wtaferner** [comment]
Thank you for reporting. I guess it has also been fixed in b71c4a3.
Let me know in case there is still an issue.
